# Generated by Django 3.0.6 on 2020-10-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_miles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles_on_car', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_type', models.CharField(max_length=100)),
                ('glass_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_age', models.IntegerField(blank=True, null=True)),
                ('year_of_purchase', models.IntegerField()),
                ('car_color', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='car_image')),
                ('insurance', models.BooleanField()),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carengine', to='cars.Car_engine')),
                ('miles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmiles', to='cars.Car_miles')),
                ('roof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carroof', to='cars.Car_roof')),
                ('servicing', models.ManyToManyField(related_name='car_services', to='cars.Car_service')),
            ],
        ),
    ]
