# Generated by Django 3.0.6 on 2020-10-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
